org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[46,)
mappings_channel=official
mappings_version=1.20.1

## Mod
mod_id=bladeofperdition
mod_name=Blade of Perdition
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.redstoneschema42.bladeofperdition
mod_authors=RedstoneSchema42
mod_description=Adds the Blade of Perdition to Minecraft.
