modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"

[[mods]]
modId="bladeofperdition"
version="1.0.0"
displayName="终焉之刃"
description='''添加了终焉之刃的模组。'''

[[dependencies.bladeofperdition]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bladeofperdition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
