modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"

[[mods]]
modId="bladeofperdition"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''

[[dependencies.bladeofperdition]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bladeofperdition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
